# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python V3.9'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      flake8 src/BlackJackClass.py --ignore=E501
    displayName: 'Run lint tests'
